name: CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        type: string

  push:

jobs:
  all:
    uses: chlbri/node-github-actions/.github/workflows/ci.yml@main
