name: CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: false
        type: string

  push:
    branches:
      - 'main'
      - 'master'

jobs:
  all:
    uses: chlbri/node-github-actions/.github/workflows/ci.yml@main
